In [2]:
import numpy as np

## Задача №1

### Перший спосіб

In [40]:
a = np.array([[1, 1, 1], [0.05, 0.07, 0], [0.05, 0, 0.06]])
a

array([[1.  , 1.  , 1.  ],
       [0.05, 0.07, 0.  ],
       [0.05, 0.  , 0.06]])

In [41]:
b = np.array([50000, 2250, 1400])
b

array([50000,  2250,  1400])

In [44]:
result = np.linalg.solve(a, b)
result

array([10000., 25000., 15000.])

### Другий спосіб

In [9]:
a_inv = np.linalg.inv(a)
a_inv

array([[ -1.82608696,  26.08695652,  30.43478261],
       [  1.30434783,  -4.34782609, -21.73913043],
       [  1.52173913, -21.73913043,  -8.69565217]])

In [11]:
result2 = a_inv.dot(b)
result2

array([10000., 25000., 15000.])

## Задача №2

### Перший спосіб

In [58]:
a = np.array([[1, 1, 1], [1, -1, 0], [1, 0, -1]])
a

array([[ 1,  1,  1],
       [ 1, -1,  0],
       [ 1,  0, -1]])

In [59]:
b = np.array([1328, -120, 100])
b

array([1328, -120,  100])

In [60]:
result = np.linalg.solve(a, b)
result

array([436., 556., 336.])

### Другий спосіб

In [61]:
a_inv = np.linalg.inv(a)
a_inv

array([[ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667,  0.33333333],
       [ 0.33333333,  0.33333333, -0.66666667]])

In [62]:
result2 = a_inv.dot(b)
result2

array([436., 556., 336.])

## Задача №3

### Перший спосіб

In [48]:
a = np.array([[3, 0, 3], [6, 1/4, 0], [1, 1/3, 1]])
a

array([[3.        , 0.        , 3.        ],
       [6.        , 0.25      , 0.        ],
       [1.        , 0.33333333, 1.        ]])

In [49]:
b = np.array([1, 1, 1])
b

array([1, 1, 1])

In [53]:
result = np.linalg.solve(a, b)
result

array([0.08333333, 2.        , 0.25      ])

In [54]:
result_coef = (1/result)**0.5
result_coef

array([3.46410162, 0.70710678, 2.        ])

### Другий спосіб

In [55]:
a_inv = np.linalg.inv(a)
a_inv

array([[ 0.04166667,  0.16666667, -0.125     ],
       [-1.        ,  0.        ,  3.        ],
       [ 0.29166667, -0.16666667,  0.125     ]])

In [56]:
result2 = a_inv.dot(b)
result2

array([0.08333333, 2.        , 0.25      ])

In [57]:
result2_coef = (1/result2)**0.5
result2_coef

array([3.46410162, 0.70710678, 2.        ])

## Задача №4

### Перший спосіб

In [63]:
a = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])
a

array([[ 1,  1,  1],
       [ 9,  3,  1],
       [ 1, -1,  1]])

In [65]:
b = np.array([12, 54, 2])
b

array([12, 54,  2])

In [67]:
result = np.linalg.solve(a, b)
result

array([4., 5., 3.])

### Другий спосіб

In [68]:
a_inv = np.linalg.inv(a)
a_inv

array([[-0.25 ,  0.125,  0.125],
       [ 0.5  , -0.   , -0.5  ],
       [ 0.75 , -0.125,  0.375]])

In [69]:
result2 = a_inv.dot(b)
result2

array([4., 5., 3.])

## Задача №5

In [71]:
import numpy as np

In [86]:
def get_polynom(coords):
    a = []
    b = []
    for x, y in coords:
        b.append(y)
        a_row = []
        for i in range(len(coords)):
            a_row.append(x ** i)
        a.append(a_row)
    return np.linalg.solve(a, b)

In [87]:
get_polynom([(1, 12), (3, 54), (-1, 2)])

array([3., 5., 4.])